---
# tasks file for create_user
- name: Create requester user
  user:
    name: "{{ user_name }}"
    comment: "user"
    createhome: yes
    generate_ssh_key: yes
    state: present
    #password: "{{ requester_pwd | default() }}"

- name: Downloading pub key
  fetch: src=/home/{{ user_name }}/.ssh/id_rsa dest=/tmp/id_rsa.tmp flat=yes

- name: enable a google authenticator
  shell: sudo -u {{ user_name }} -H sh -c "yes | google-authenticator"
- name: IP Address
  shell: curl ident.me
  register: ip

- name: Send email to requester user
  mail:
    host: localhost
    port: 25
    subject: Nutanix Bation serverIP:{{ip.stdout}}
    body: Hi {{ user_name }}, PFA Private key and Google_authenticator codes
    from: jayagopal.reddy@minjar.com
    to: "{{ email_id }}"
    attach:
      - /home/{{ user_name }}/.ssh/id_rsa
      - /home/{{ user_name }}/.google_authenticator
  #delegate_to: localhost
